### ISSUE TITLE
Bug fix for: VideoSort: IndexError: string index out of range

### ISSUE THREAD

**Issue by SoftwareByMark** [nzbget/VideoSort#32]
First off - thanks for a great script!  I've been using it since 2015!  I recently upgraded my Nzbget version and updated this script to v6.1.  But I ran into a bug:

```
ERROR | Thu Nov 30 2017 09:01:46 | Post-process-script videosort/VideoSort.py for b15a17b49b4444d3861a513dae5925db failed
ERROR | Thu Nov 30 2017 09:01:46 | VideoSort: string index out of range
ERROR | Thu Nov 30 2017 09:01:46 | VideoSort: Failed: b15a17b49b4444d3861a513dae5925db.mkv
INFO | Thu Nov 30 2017 09:01:46 | VideoSort: IndexError: string index out of range
INFO | Thu Nov 30 2017 09:01:46 | VideoSort: if len(path) > 0 and path.strip()[0] in '/\\':
INFO | Thu Nov 30 2017 09:01:46 | VideoSort: File "/Users/media/Library/Application Support/NZBGet/scripts/videosort/VideoSort.py", line 651, in strip_folders
INFO | Thu Nov 30 2017 09:01:46 | VideoSort: path = strip_folders(path)
INFO | Thu Nov 30 2017 09:01:46 | VideoSort: File "/Users/media/Library/Application Support/NZBGet/scripts/videosort/VideoSort.py", line 1129, in construct_path
INFO | Thu Nov 30 2017 09:01:46 | VideoSort: new_path = construct_path(old_path)
INFO | Thu Nov 30 2017 09:01:46 | VideoSort: File "/Users/media/Library/Application Support/NZBGet/scripts/videosort/VideoSort.py", line 1180, in <module>
INFO | Thu Nov 30 2017 09:01:46 | VideoSort: Traceback (most recent call last):
```

I made the following code change on line 651 to fix this issue - I added the condition **len(path.strip()) > 0** to the if statement.  That seems to have fixed it up.

```
    # For path beginning with a slash, insert empty element to prevent loss
    if len(path.strip()) > 0 and path.strip()[0] in '/\\':
        f.insert(0, '')
```

**Comment by hugbug** [comment]
Great. Could you create a pull request?

**Comment by SoftwareByMark** [comment]
Done

**Comment by hugbug** [comment]
Thank you!
