### ISSUE TITLE
VideoSort not completing post processing

### ISSUE THREAD

**Issue by jeells102** [nzbget/VideoSort#48]
Hi,

I've got videosort enabled and it's not able to complete my post processing. Below is the log that is generated;

`INFO | Tue Aug 06 2019 16:44:19 | Collection 8.Out.Of.10.Cats.Does.Countdown.S18E02.1080p.HEVC.x265-MeGusta-Obfuscated removed from history
-- | -- | --
INFO | Tue Aug 06 2019 16:44:19 | Deleting file /home/jeells102/nzbget/downloads/nzb/8.Out.Of.10.Cats.Does.Countdown.S18E02.1080p.HEVC.x265-MeGusta-Obfuscated.nzb.queued
INFO | Tue Aug 06 2019 16:44:19 | Deleting 8.Out.Of.10.Cats.Does.Countdown.S18E02.1080p.HEVC.x265-MeGusta-Obfuscated from history
INFO | Tue Aug 06 2019 16:43:28 | Collection 8.Out.Of.10.Cats.Does.Countdown.S18E02.1080p.HEVC.x265-MeGusta-Obfuscated added to history
ERROR | Tue Aug 06 2019 16:43:28 | Post-process-script videosort/VideoSort.py for 8.Out.Of.10.Cats.Does.Countdown.S18E02.1080p.HEVC.x265-MeGusta-Obfuscated failed (terminated with unknown status)
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: ValueError: A 0.7-series setuptools cannot be installed with distribute. Found one at /usr/lib/python2.7/dist-packages
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: "with distribute. Found one at %s" % str(self.location))
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: File "/home/jeells102/nzbget/scripts/videosort/lib/pkg_resources.py", line 2374, in insert_on
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: self.insert_on(path)
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: File "/home/jeells102/nzbget/scripts/videosort/lib/pkg_resources.py", line 2273, in activate
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: add_activation_listener(lambda dist: dist.activate())
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: File "/home/jeells102/nzbget/scripts/videosort/lib/pkg_resources.py", line 2841, in <lambda>
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: callback(dist)
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: File "/home/jeells102/nzbget/scripts/videosort/lib/pkg_resources.py", line 710, in subscribe
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: add_activation_listener(lambda dist: dist.activate())
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: File "/home/jeells102/nzbget/scripts/videosort/lib/pkg_resources.py", line 2841, in <module>
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: from pkg_resources import iter_entry_points, EntryPoint
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: File "/home/jeells102/nzbget/scripts/videosort/lib/babelfish/converters/__init__.py", line 6, in <module>
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: File "/home/jeells102/nzbget/scripts/videosort/lib/babelfish/__init__.py", line 20, in <module>
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: import babelfish
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: File "/home/jeells102/nzbget/scripts/videosort/lib/guessit/rules/properties/language.py", line 10, in <module>
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: from .language import SubtitlePrefixLanguageRule, SubtitleSuffixLanguageRule, SubtitleExtensionRule
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: File "/home/jeells102/nzbget/scripts/videosort/lib/guessit/rules/properties/title.py", line 11, in <module>
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: from .title import TitleFromPosition
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: File "/home/jeells102/nzbget/scripts/videosort/lib/guessit/rules/properties/episodes.py", line 14, in <module>
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: from .properties.episodes import episodes
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: File "/home/jeells102/nzbget/scripts/videosort/lib/guessit/rules/__init__.py", line 11, in <module>
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: from .rules import rebulk_builder
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: File "/home/jeells102/nzbget/scripts/videosort/lib/guessit/api.py", line 17, in <module>
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: from .api import guessit, GuessItApi
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: File "/home/jeells102/nzbget/scripts/videosort/lib/guessit/__init__.py", line 6, in <module>
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: import guessit
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: File "/home/jeells102/nzbget/scripts/videosort/VideoSort.py", line 271, in <module>
INFO | Tue Aug 06 2019 16:43:28 | VideoSort: Traceback (most recent call last):
INFO | Tue Aug 06 2019 16:43:28 | Executing post-process-script videosort/VideoSort.py for 8.Out.Of.10.Cats.Does.Countdown.S18E02.1080p.HEVC.x265-MeGusta-Obfuscated
`

I'm running a Linux Ubuntu 16.04.6 LTS server with QuickBox installed on too. 

Thanks

**Comment by fleXible** [comment]
Hello @jeells102,

this is a well known issue with setuptools-20.7 and can easily be fixed by updating them.
Try: `pip install --upgrade setuptools`

For further information please refer to:
- https://github.com/pypa/setuptools/issues/543
- https://askubuntu.com/questions/762768/how-to-get-pip-functional-again
