### ISSUE TITLE
Videosort fails after nzbget upgrade

### ISSUE THREAD

**Issue by staki1966** [nzbget/VideoSort#7]
I've been using a version of videosort (not sure which one) with nzbget 14.2 for a long time withouth any issues. Yesterday I upgraded nzbget to current version 16.4. That wiped out videosort, so I reinstalled it and am running 6.1 now. Since then, postprocessing of every downloaded file fails, with the log:

```
Mon Dec  7 08:52:32 2015	INFO	Executing post-process-script videosort/VideoSort.py for Homeland.S05E10.720p.HDTV.x264-0SEC
Mon Dec  7 08:52:41 2015	INFO	VideoSort: Traceback (most recent call last):
Mon Dec  7 08:52:41 2015	INFO	VideoSort:   File "/share/MD0_DATA/.qpkg/NZBGet/nzbget/scripts/videosort/VideoSort.py", line 1180, in <module>
Mon Dec  7 08:52:41 2015	INFO	VideoSort:     new_path = construct_path(old_path)
Mon Dec  7 08:52:41 2015	INFO	VideoSort:   File "/share/MD0_DATA/.qpkg/NZBGet/nzbget/scripts/videosort/VideoSort.py", line 1065, in construct_path
Mon Dec  7 08:52:41 2015	INFO	VideoSort:     guess = guess_info(filename)
Mon Dec  7 08:52:41 2015	INFO	VideoSort:   File "/share/MD0_DATA/.qpkg/NZBGet/nzbget/scripts/videosort/VideoSort.py", line 980, in guess_info
Mon Dec  7 08:52:41 2015	INFO	VideoSort:     matcher = guessit.matcher.IterativeMatcher(unicode(guessfilename), filetype='autodetect', options={'nolanguage': True, 'nocountry': True})
Mon Dec  7 08:52:41 2015	INFO	VideoSort:   File "/share/MD0_DATA/.qpkg/NZBGet/nzbget/scripts/videosort/lib/guessit/matcher.py", line 110, in __init__
Mon Dec  7 08:52:41 2015	INFO	VideoSort:     from guessit.plugins import transformers
Mon Dec  7 08:52:41 2015	INFO	VideoSort:   File "/share/MD0_DATA/.qpkg/NZBGet/nzbget/scripts/videosort/lib/guessit/plugins/transformers.py", line 212, in <module>
Mon Dec  7 08:52:41 2015	INFO	VideoSort:     reload()
Mon Dec  7 08:52:41 2015	INFO	VideoSort:   File "/share/MD0_DATA/.qpkg/NZBGet/nzbget/scripts/videosort/lib/guessit/plugins/transformers.py", line 210, in reload
Mon Dec  7 08:52:41 2015	INFO	VideoSort:     reload_options(all_transformers())
Mon Dec  7 08:52:41 2015	INFO	VideoSort:   File "/share/MD0_DATA/.qpkg/NZBGet/nzbget/scripts/videosort/lib/guessit/options.py", line 70, in reload
Mon Dec  7 08:52:41 2015	INFO	VideoSort:     _opts, _naming_opts, _output_opts, _information_opts, _webservice_opts, _other_opts = build_opts(transformers)
Mon Dec  7 08:52:41 2015	INFO	VideoSort:   File "/share/MD0_DATA/.qpkg/NZBGet/nzbget/scripts/videosort/lib/guessit/options.py", line 63, in build_opts
Mon Dec  7 08:52:41 2015	INFO	VideoSort:     transformer.register_options(opts, naming_opts, output_opts, information_opts, webservice_opts, other_opts)
Mon Dec  7 08:52:41 2015	INFO	VideoSort:   File "/share/MD0_DATA/.qpkg/NZBGet/nzbget/scripts/videosort/lib/guessit/transfo/expected_series.py", line 37, in register_options
Mon Dec  7 08:52:41 2015	INFO	VideoSort:     help='List of expected series to parse. Separate series names with ";"')
Mon Dec  7 08:52:41 2015	INFO	VideoSort:   File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/optparse.py", line 1018, in add_option
Mon Dec  7 08:52:41 2015	INFO	VideoSort:     raise TypeError, "invalid arguments"
Mon Dec  7 08:52:41 2015	INFO	VideoSort: TypeError: invalid arguments
Mon Dec  7 08:52:41 2015	INFO	VideoSort: Skipping small: sample-homeland.s05e10.720p.hdtv.x264-0sec.mkv
Mon Dec  7 08:52:41 2015	ERROR	VideoSort: Failed: Homeland.S05E10.720p.HDTV.x264-0SEC.mkv
Mon Dec  7 08:52:41 2015	ERROR	VideoSort: invalid arguments
```

**Comment by hugbug** [comment]
Please update your Python. It's too old for current version of guessit, the library VideoSort relies on.
You can also use an older versions of VideoSort if it was sufficient for your needs.

Also try asking on [QNAP forum - NZBGet section](http://forum.qnap.com/viewforum.php?f=141).

**Comment by staki1966** [comment]
Most recent "official" python version for qnap (2.7.3) is already installed on my system, so I searched QNAP forum as suggested and found [this](http://forum.qnap.com/viewtopic.php?p=476175#p476175). I downgraded videosort to 5.0 and can confirm it is working fine.

Thanks for the fast response!
