### ISSUE TITLE
ImportError: No module named patterns.extension

### ISSUE THREAD

**Issue by JohnnyUSA** [nzbget/VideoSort#8]
Hi guys and thanks for this wonderful script.

Worked fine for me until 2 days ago when it seems to fail with this error:

```
info Sat Feb 20 2016 00:08:04 videosort: ImportError: No module named patterns.extension 
info Sat Feb 20 2016 00:08:04 videosort: import guessit.patterns.extension 
info Sat Feb 20 2016 00:08:04 videosort: File "/opt/nzbget/scripts/videosort/videosort.py", line 254, in <module> 
info Sat Feb 20 2016 00:08:04 videosort: Traceback (most recent call last): 

```

Python version is:

```
root@xxx-nas:~# python -V
Python 2.7.9

```

I've tried to google around and no fix.. you're my last hope.

Thanks in advance!

**Comment by hugbug** [comment]
Replied you on forum.

**Comment by JohnnyUSA** [comment]
Hi and thanks for your reply, your 2nd suggestion saved me:

Replacing
`sys.path.append(dirname(__file__) + '/lib')`
with
`sys.path.insert(1, dirname(__file__) + '/lib')`
in videosort.py, did the trick. Script is working now.

However, i still get a warning:
`videosort: /opt/nzbget/scripts/videosort/lib/guessit/__init__.py:23: UserWarning: Module guessit was already imported from /opt/nzbget/scripts/videosort/lib/guessit/__init__.pyc, but /usr/local/lib/python2.7/dist-packages is being added to sys.path`

Something to worry about? Cheers!

**Comment by hugbug** [comment]
As long as it works I think you can safely ignore the message.

**Comment by JohnnyUSA** [comment]
Ok thanks, closing it for now ;)

**Comment by mourningsun75** [comment]
Hi,

Replacing
sys.path.append(dirname(__file__) + '/lib')
with
sys.path.insert(1, dirname(__file__) + '/lib')

for me it is not working. :-(

Now i got the following error:

`VideoSort: ValueError: A 0.7-series setuptools cannot be installed with distribute. Found one at /usr/local/lib/python2.7/dist-packages`

**Comment by mourningsun75** [comment]
It works when i uninstall guessit, but guessit is required by other other software

**Comment by hugbug** [comment]
Your system version of guessit should not be used at all. Check again if the **videosort.py** were edited correctly with "sys.path.insert". And of course make sure you have the whole videosort-folder including lib-subdirectory and not just videosort.py.

**Comment by mourningsun75** [comment]
Test 1:
```
sys.path.append(dirname(__file__) + '/lib')
#sys.path.insert(1, dirname(__file__) + '/lib')

```
Error:
`VideoSort: ImportError: No module named patterns.extension`

Test 2:
```
#sys.path.append(dirname(__file__) + '/lib')
sys.path.insert(1, dirname(__file__) + '/lib')

```

Error:
```
VideoSort: /home/xxx/nzbget/plugins/videosort/lib/guessit/__init__.py:23: UserWarning: Module guessit was already imported from /home/xxx/nzbget/plugins/videosort/lib/guessit/__init__.pyc, but /usr/local/lib/python2.7/dist-packages is being added to sys.path

VideoSort: ValueError: A 0.7-series setuptools cannot be installed with distribute. Found one at /usr/local/lib/python2.7/dist-packages
```

**Comment by mourningsun75** [comment]
"And of course make sure you have the whole videosort-folder including lib-subdirectory and not just videosort.py." -> Checked, everthing is there

**Comment by hugbug** [comment]
Is this an error at all? Not a warning? I don't see call stack printed.

I'm afraid I can't help you more here as I'm not very experienced with python. I have general debug skills but I need to put my hands on the system to try things.

**Comment by mourningsun75** [comment]
Here is the stack

```
Thu Apr 14 14:41:10 2016        INFO    nzbget 16.4 daemon-mode
Thu Apr 14 14:41:10 2016        INFO    Scheduler: pausing download
Thu Apr 14 14:41:24 2016        INFO    XYZ returned from history back to download queue
Thu Apr 14 14:41:24 2016        INFO    Queueing XYZ for post-processing
Thu Apr 14 14:41:24 2016        INFO    Cleaning up XYZ
Thu Apr 14 14:41:24 2016        INFO    Nothing to cleanup for XYZ
Thu Apr 14 14:41:25 2016        INFO    Executing post-process-script videosort/VideoSort.py for XYZ
Thu Apr 14 14:41:25 2016        INFO    VideoSort: /home/xxx/nzbget/plugins/videosort/lib/guessit/__init__.py:23: UserWarning: Module guessit was already imported from /home/mourningsun75/nzb_databases/nzbget/plugins/videosort/lib/guessit/__init__.pyc, but /usr/local/lib/python2.7/dist-packages is being added to sys.path
Thu Apr 14 14:41:25 2016        INFO    VideoSort:   import pkg_resources
Thu Apr 14 14:41:25 2016        INFO    VideoSort: Traceback (most recent call last):
Thu Apr 14 14:41:25 2016        INFO    VideoSort:   File "/home/xxx/nzbget/plugins/videosort/VideoSort.py", line 254, in <module>
Thu Apr 14 14:41:25 2016        INFO    VideoSort:     import guessit
Thu Apr 14 14:41:25 2016        INFO    VideoSort:   File "/home/xxx/nzbget/plugins/videosort/lib/guessit/__init__.py", line 23, in <module>
Thu Apr 14 14:41:25 2016        INFO    VideoSort:     import pkg_resources
Thu Apr 14 14:41:25 2016        INFO    VideoSort:   File "/home/xxx/nzbget/plugins/videosort/lib/pkg_resources.py", line 2841, in <module>
Thu Apr 14 14:41:25 2016        INFO    VideoSort:     add_activation_listener(lambda dist: dist.activate())
Thu Apr 14 14:41:25 2016        INFO    VideoSort:   File "/home/xxx/nzbget/plugins/videosort/lib/pkg_resources.py", line 710, in subscribe
Thu Apr 14 14:41:25 2016        INFO    VideoSort:     callback(dist)
Thu Apr 14 14:41:25 2016        INFO    VideoSort:   File "/home/xxx/nzbget/plugins/videosort/lib/pkg_resources.py", line 2841, in <lambda>
Thu Apr 14 14:41:25 2016        INFO    VideoSort:     add_activation_listener(lambda dist: dist.activate())
Thu Apr 14 14:41:25 2016        INFO    VideoSort:   File "/home/xxx/nzbget/plugins/videosort/lib/pkg_resources.py", line 2273, in activate
Thu Apr 14 14:41:25 2016        INFO    VideoSort:     self.insert_on(path)
Thu Apr 14 14:41:25 2016        INFO    VideoSort:   File "/home/xxx/nzbget/plugins/videosort/lib/pkg_resources.py", line 2374, in insert_on
Thu Apr 14 14:41:25 2016        INFO    VideoSort:     "with distribute. Found one at %s" % str(self.location))
Thu Apr 14 14:41:25 2016        INFO    VideoSort: ValueError: A 0.7-series setuptools cannot be installed with distribute. Found one at /usr/local/lib/python2.7/dist-packages
Thu Apr 14 14:41:25 2016        ERROR   Post-process-script videosort/VideoSort.py for XYZ failed (terminated with unknown status)
Thu Apr 14 14:41:25 2016        INFO    Executing post-process-script Logger.py for XYZ
Thu Apr 14 14:41:25 2016        INFO    Post-process-script Logger.py for XYZ successful
Thu Apr 14 14:41:25 2016        INFO    Executing post-process-script EMail.py for XYZ
Thu Apr 14 14:41:25 2016        DETAIL  EMail: Script successfully started
Thu Apr 14 14:41:25 2016        DETAIL  EMail: Sending E-Mail
Thu Apr 14 14:41:27 2016        INFO    Post-process-script EMail.py for XYZ successful
Thu Apr 14 14:41:27 2016        INFO    Collection XYZ added to history

```

**Comment by mourningsun75** [comment]
The combination:

sudo pip uninstall guessit

and 

sys.path.append(dirname(__file__) + '/lib')

works perfect.

But not for other tools and scripts

**Comment by hugbug** [comment]
Make another: use "sys.path.insert" and delete file "videosort/lib/pkg_resources.py".

**Comment by mourningsun75** [comment]
Same Stack

**Comment by hugbug** [comment]
>Same Stack

I don't believe you  :cop: 
Post it.

**Comment by mourningsun75** [comment]
you are right!

know it seems to work!

**Comment by hugbug** [comment]
**TODO:**
- use "insert" instead of "append";
- use system "pkg_resources.py" and fall back to "lib/pkg_resources.py" only if a system module doesn't exist.

**Comment by hugbug** [comment]
**DONE:**
- use "insert" instead of "append";

**TODO:**
- use system "pkg_resources.py" and fall back to "lib/pkg_resources.py" only if a system module doesn't exist.
